export type OfficialAnthropometrySource = "bio" | "skinfold" | null;

export type MeasurementForm = {
  assessment_date: string;
  weight?: string;
  height?: string;
  bio_fat_pct?: string;
  bio_lean_kg?: string;
  visceral_fat?: string;
  sf_pectoral?: string;
  sf_midaxillary?: string;
  sf_triceps?: string;
  sf_biceps?: string;
  sf_subscapular?: string;
  sf_suprailiac?: string;
  sf_abdominal?: string;
  sf_thigh_sf?: string;
  sf_calf_sf?: string;
  neck?: string;
  shoulder?: string;
  chest?: string;
  waist?: string;
  abdomen?: string;
  hip?: string;
  arm_relax_r?: string;
  arm_relax_l?: string;
  arm_contract_r?: string;
  arm_contract_l?: string;
  forearm_r?: string;
  forearm_l?: string;
  wrist_r?: string;
  wrist_l?: string;
  thigh_prox_r?: string;
  thigh_prox_l?: string;
  thigh_r?: string;
  thigh_l?: string;
  calf_r?: string;
  calf_l?: string;
  notes?: string;
};
